# Generated by Django 5.2.5 on 2025-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningresult',
            name='family_history',
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='jaundice',
            field=models.IntegerField(),
        ),
    ]
